routes/web.php
<?php

use App\Http\Controllers\LoginController;
use App\Http\Controllers\TaskController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
 */

Route::get('/', function () {
    return view('/login');
});
Route::resource('/tasks', TaskController::class);
// Route::prefix('/tasks')->name('tasks.')->group(function () {
//     Route::get('/', [TaskController::class, 'index'])->name('index');
//     Route::post('/', [TaskController::class, 'store'])->name('store');
//     Route::get('/create', [TaskController::class, 'create'])->name('create');
//     Route::get('/{id}', [TaskController::class, 'show'])->name('show');
//     Route::put('/{id}', [TaskController::class, 'update'])->name('update');
//     Route::delete('/{id}', [TaskController::class, 'destroy'])->name('destroy');
//     Route::put('/{id}/edit', [TaskController::class, 'edit'])->name('edit');
// });
Route::get('/login', [LoginController::class, 'show'])->name('login');
Route::post('/login', [LoginController::class, 'authenticate'])->name('login.authenticate');
Route::get('/logout', [LoginController::class, 'logout'])->name('logout');
Route::fallback(function(){ abort(404); });

resources/views/header.blade.php
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="#">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('tasks.index') }}">Task</a>
                </li>
                @guest
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('login') }}">Login</a>
                </li>
                @endguest
                @auth
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('tasks.create') }}">Create Task</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('logout') }}">Log out</a>
                </li>
                @endauth
            </ul>
            <form class="d-flex" action="{{route('tasks.index')}}" method="GET">
                <input class="form-control me-2" name="search" type="search" placeholder="Search" aria-label="Search" value="{{request()->search}}">
                <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
        </div>
    </div>
</nav>

resources/views/login.blade.php
@extends('master')
@section('main')
    <div class="container">
        <h2 class="text-center">Login</h2>
        <div class="container d-flex justify-content-center">
            <form action="{{ route('login.authenticate') }}" style="max-width: 25rem;" method="POST">
                @csrf
                @if (session('errors'))
                    <div class="alert alert-danger">{{ session('errors') }}</div>
                @endif
                <div class="mb-3">
                    <label for="email" class="form-label">Email</label>
                    <input type="email" class="form-control" id="email" name="email" value="{{ old('email') }}">
                </div>
                <div class="mb-3">
                    <label for="password" class="form-label">Password</label>
                    <input type="password" class="form-control" id="password" name="password">
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>
@endsection

resources/views/master.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>Laravel</title>
</head>

<body>
    <div class="">
        @include('header')
    </div>

    <div class="container my-3">
        @yield('main')
    </div>
</body>

</html>