routes/web.php
<?php

use App\Http\Controllers\LoginController;
use App\Http\Controllers\TaskController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
 */

Route::get('/', function () {
    return view('/login');
});
Route::resource('/tasks', TaskController::class);
// Route::prefix('/tasks')->name('tasks.')->group(function () {
//     Route::get('/', [TaskController::class, 'index'])->name('index');
//     Route::post('/', [TaskController::class, 'store'])->name('store');
//     Route::get('/create', [TaskController::class, 'create'])->name('create');
//     Route::get('/{id}', [TaskController::class, 'show'])->name('show');
//     Route::put('/{id}', [TaskController::class, 'update'])->name('update');
//     Route::delete('/{id}', [TaskController::class, 'destroy'])->name('destroy');
//     Route::put('/{id}/edit', [TaskController::class, 'edit'])->name('edit');
// });
Route::get('/login', [LoginController::class, 'show'])->name('login');
Route::post('/login', [LoginController::class, 'authenticate'])->name('login.authenticate');
Route::get('/logout', [LoginController::class, 'logout'])->name('logout');
Route::fallback(function(){ abort(404); });

app/Models/Task.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Task extends Model
{
    use HasFactory;
    protected $table = "tasks";

    protected $fillable = [
        'name',
        'content',
    ];
}

app/Http/Controllers/TaskController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\TaskRequest;
use App\Models\Task;
use Illuminate\Http\Response;
use Illuminate\Http\Request;

class TaskController extends Controller
{
    protected $task;

    public function __construct(Task $task)
    {
        $this->task = $task;
        $this->middleware('auth', ['except' => ['index', 'show']]);
    }

    /**
     * Display a listing of the resource.
     */
    public function index(Request $request)
    {
        $search = $request->search;
        $existsSpecialCharacterPerCent = preg_match('/[%]/', $search);
        $search = preg_replace('/[%]/', '\%', $search);
        $search = '%'.preg_replace('/\s+/', ' ', $search).'%';
        $tasks = Task::where('name', 'like', $search)
                ->orWhere('content', 'like', $search)
                ->latest('id')
                ->paginate(5)->withQueryString();

        return response()->view('tasks.index', compact('tasks'), 200);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return response()->view('tasks.create');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(TaskRequest $request)
    {
        $dataCreate = $request->all();

        $this->task->create($dataCreate);

        return redirect()->route('tasks.index')->withStatus(Response::HTTP_CREATED);
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        $task = Task::findOrFail($id);
        return response()->view('tasks.show', compact('task'));
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Request $request, string $id)
    {
        $task = Task::findOrFail($id);

        $queryBeforeUpdate = explode('?', url()->previous())[1];
        if (isset($queryBeforeUpdate)) {
            session(['queryURL' => $queryBeforeUpdate]);
        }
        return response()->view('tasks.edit', compact('task'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(TaskRequest $request, string $id)
    {
        $task = Task::findOrFail($id);
        $dataUpdate = [
            'name' => $request->name,
            'content' => $request->content,
        ];

        $queryURL = explode('&', session('queryURL'));
        $task->update($dataUpdate);
        return redirect()->route('tasks.index', $queryURL)->withStatus(Response::HTTP_OK);
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        $task = Task::findOrFail($id);

        $task->delete();
        session()->flash('message', 'delete success');

        return back();
    }
}

resources/views/tasks/create.blade.php
@extends('master')
@section('main')
    <form action="{{ route('tasks.store') }}" method="POST" >
        @csrf
        <div class="mb-3">
            <label for="name" class="form-label">Name</label>
            <input type="text" class="form-control" id="name" name="name" value="{{ old('name') }}">
            @error('name')
                <div class="text-danger">{{ $message }}</div>
            @enderror
        </div>

        <div class="mb-3">
            <label for="content" class="form-label">Content</label>
            <input type="text" class="form-control" id="content" name="content" value="{{ old('content') }}">
            @error('content')
                <div class="text-danger">{{ $message }}</div>
            @enderror
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
@endsection

resources/views/tasks/edit.blade.php
@extends('master')
@section('main')
    <form action="{{ route('tasks.update', $task->id) }}" method="POST">
        @csrf
        @method('PUT')
        <div class="mb-3">
            <label for="name" class="form-label">Name</label>
            <input type="text" class="form-control" id="name" name="name"
                value="{{ old('name', $task->name) }}">
            @error('name')
                <div class="text-danger">{{ $message }}</div>
            @enderror
        </div>
        <div class="mb-3">
            <label for="content" class="form-label">Content</label>
            <input type="text" class="form-control" id="content" name="content"
            value="{{ old('content', $task->content) }}"
            >
            @error('content')
                <div class="text-danger">{{ $message }}</div>
            @enderror
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
@endsection

resources/views/tasks/index.blade.php
@extends('master')
@section('main')
    @if (session('message'))
        <div class="alert alert-success">
            {{ session('message') }}
        </div>
    @endif
    <table class="table table-hover">
        <tr class="text-center">
            <th>ID</th>
            <th>Name</th>
            <th>Content</th>
            <th>Action</th>
        </tr>
        @foreach ($tasks as $task)
            <tr>
                <td>{{ $task->id }}</td>
                <td><a href="{{ route('tasks.show', $task->id) }}">{{ $task->name }}</a></td>
                <td>{{ $task->content }}</td>
                <td>
                    <a href="{{ route('tasks.edit', $task->id) }}" class="btn btn-primary">Update</a>
                    <form action="{{ route('tasks.destroy', $task->id) }}" method="POST" onsubmit="return confirm('are you sure?')">
                        @csrf
                        @method('DELETE')
                        <button type="submit" class="btn btn-warning">Delete</button>
                    </form>
                </td>
            </tr>
        @endforeach
    </table>
    {{$tasks->links()}}
    </div>
@endsection

resources/views/tasks/show.blade.php
@extends('master')
@section('main')
    <table class="table table-hover">
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Content</th>
            <th>Action</th>
        </tr>
        <tr>
            <td>{{ $task->id }}</td>
                <td><a href="{{ route('tasks.show', $task->id) }}">{{ $task->name }}</a></td>
                <td>{{ $task->content }}</td>
                <td>
                    <a href="{{ route('tasks.edit', $task->id) }}" class="btn btn-primary">Update</a>
                    <form action="{{ route('tasks.destroy', $task->id) }}" method="POST">
                        @csrf
                        @method('DELETE')
                        <button type="submit" class="btn btn-warning">Delete</button>
                    </form>
                </td>
        </tr>
    </table>
@endsection